openapi: 3.0.3
info:
  version: '2.0.0'
  title: API för digitala fullmakter
  description: |
    ## Introduktion
    API som anslutna parter kan använda för att hämta och söka digitala behörigheter och fullmakter.

    Generellt gäller att en ansluten part endast får hämta de behörigheter och fullmakter som gäller hos dem.
    Tredje man i denna specifikation avser ansluten part (som är benämningen i övrig dokumentation kring Mina ombud).

    ## Headers
    Vissa headers är gemensamma för alla API-anrop.

    | Header         | Obligatorisk | Beskrivning                                                               |
    |----------------|--------------|---------------------------------------------------------------------------|
    | Authorization  | Ja           | Används för att skicka access token.                                      |
    | X-Service-Name | Ja           | Namn på anropande e-tjänst. Tillåtna tecken: [a-zA-Z0-9._-].              |
    | X-Id-Token     | Beroende på scope. | Information om slutanvändaren som en signerad JWT (RFC 7515).       |
    | X-Request-Id   | Nej          | Unikt ID för anropet av typen UUID. Returneras i svaret och i [ApiError](#model-ApiError). |

    ## Null
    Attribut som inte är obligatoriska (inte markerade som `required`) ska inte serialiseras
    till JSON som null. Endast attribut markerade `nullable` ska serialiseras som null.

    Hur detta konfigureras beror på vilket JSON-ramverk som används.

    ## Bakåtkompatibilitet
    API-konsumenter måste kunna hantera bakåtkompatibla ändringar i API:ets datamodell.

    Det innebär att tillägg av icke-obligatoriska attribut i API-svar inte anses som brytande
    förändringar.

    Konfigurera eventuellt JSON-bibliotek och schema-validering att acceptera okända attribut.

    ## Ändringar i 2.0.0

    - Attributet `typer` har tagits bort från [Behorighetsobjekt](#model-Behorighetsobjekt).
    - Typerna BehorighetTyp och BehorighetTypConstraint har tagits bort.
    - Beskrivning från BehorighetTyp har flyttats till [Behorighetsobjekt](#model-Behorighetsobjekt).
    - Attributet `rubrik` i [Behorighetsobjekt](#model-Behorighetsobjekt) har gjorts obligatoriskt.
    - Listan `behorigheter` i [Fullmakt](#model-Fullmakt) har nu element av typen [Behorighetsobjekt](#model-Behorighetsobjekt)
      istället för den extra nästlingen under typen Behorighet som fanns i tidigare version.
      Typen Behorighet har tagits bort.
    - Attributet `typ` har tagits bort från [UtdeladBehorighet](#model-UtdeladBehorighet).
      Berör svar från API för att söka behörigheter.

    Tidigare version av [Fullmakt](#model-Fullmakt):
    ```json
    {
      "fullmakt": {
        "behorigheter": [
          {
            "behorighetsobjekt": {
              "kod": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "typer": [
                {
                  "typ": "aktiv",
                  "rubrik": "Foo",
                  "beskrivning": "Foo bar baz",
                  "vald": true,
                  "niva": 0
                }
              ]
            }
          }
        ]
      }
    }
    ```

    I version 2 är strukturen utplattad och innehåller inte behörighetstyper:
    ```json
    {
      "fullmakt": {
        "behorigheter": [
          {
            "kod": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "rubrik": "Foo",
            "beskrivning": "Foo bar baz",
          }
        ]
      }
    }
    ```

    ## Ändringar i 1.2.0

    Stöd för transportfullmakter (vidaredelning av fullmakter).

    Ny parameter `utdelning` i [GET /tredjeman/{tredjeman}/fullmakter/{fullmakt}](#operations-fullmakter-hamtaFullmakt)
    för att begära information om transportfullmakter. Om parametern anges returneras det nya attributet `utdelningar`
    i [FullmaktMetadata](#model-FullmaktMetadata).

    Nytt attribut `vidaredelning` i [Fullmakt](#model-Fullmakt).

    Nytt attribut `vidaredelad` i [FullmaktMetadata](#model-FullmaktMetadata).

    Nya attribut i [FullmaktListItem](#model-FullmaktListItem):
    - vidaredelad
    - vidaredelning
    - transportfullmakt

security:
- BearerAuth: []
- OAuth2: []

tags:
- name: fullmakter
  description: Sök och agera med digitala fullmakter
- name: signering
  description: Publika nycklar för signerad information

paths:
  /tredjeman/{tredjeman}/fullmakter/{fullmakt}:
    parameters:
    - name: tredjeman
      in: path
      required: true
      description: Identitet för den tredje man som håller fullmakten
      schema:
        $ref: '#/components/schemas/Organisationsnummer'
    - name: fullmakt
      in: path
      required: true
      description: Den fullmakt som frågan gäller
      schema:
        $ref: '#/components/schemas/FullmaktId'
    get:
      summary: Hämta en fullmakt
      description: Hämta en specifik fullmakt hos tredje man.
      operationId: hamtaFullmakt
      tags:
      - fullmakter
      responses:
        '200':
          description: Lyckad hämtning av fullmaktsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullmaktMetadataResponse'
              examples:
                giltig:
                  summary: Giltig fullmakt
                  value: {"fullmakt": {"id": "b278cd9b-913f-470e-b75c-3406a0f46e53",
                      "ursprung": {"mall": "04130a69-ea74-43b4-b8f4-b456d5032a71"},
                      "rubrik": "Restaurangombud", "beskrivning": "Ombud som får vara
                        behjälpligt att fylla i ansökningar och anmälningar vid start/drift
                        och avslut kringtillstånd att sälja alkohol och tobak i verksamheten.",
                      "skapare": {"id": "195206142597", "typ": "pnr", "namn": "Greger",
                        "fornamn": "Nina"}, "tredjeman": {"id": "2120000829", "namn": "Karlskrona
                          kommun"}, "fullmaktsgivare": {"id": "5561733360", "typ": "orgnr",
                        "namn": "Stora Enso AB"}, "fullmaktsgivarroll": "ORGANISATION",
                      "fullmaktshavare": [{"id": "198101052382", "typ": "pnr", "namn": "Persson",
                          "fornamn": "Test"}], "signatarer": ["fysiskPerson": {"id": "195206142597",
                            "typ": "pnr", "namn": "Greger", "fornamn": "Nina"}], "behorigheter": [
                        {"kod": "6f3440ec-76ef-4a3b-9379-f11f0d76d887", "rubrik": "Anmälan
                            om försäljning och servering av folköl", "beskrivning": "Behörighet
                            att fylla i, signera och skicka in anmälan om folkölsförsäljning."}],
                      "giltigFrom": "2022-09-07", "transportfullmakt": false, "giltigTom": "2024-09-06",
                      "skapadTidpunkt": "2022-09-07T14:24:30.073899+02:00"}, "metadata": {
                      "referensnummer": "MOF0000001553", "registreringstidpunkt": "2022-09-07T14:25:05.983776+02:00",
                      "status": "GILTIG", "underskrifter": [{"person": {"id": "195206142597",
                            "typ": "pnr", "namn": "Greger", "fornamn": "Nina"}, "tidpunkt": "2022-09-07T14:25:01.9088902+02:00"}]},
                    "svarstidpunkt": "2022-11-28T13:23:04.346531+01:00", "_sig": {
                      "protected": "eyJraWQiOiI1NTdiMjYyOTZiN2U3ZmJlNDFkMDcxMWIyMWMyZDdiZjg4MDQ1MDdhIiwiYWxnIjoiUlMyNTYifQ",
                      "signature": "U9Y9VT1KZbhtPxo8LQm9454kA0vBJz_iQbNVyuHYkU-tB0SQpNHw3YaGdQiO9Va03InTE-Wu3yD9cs7y4VeLnQPLBkoI_pkdGNBEe6W4Rby_FtWF4bntMPUg6uNRvuqt8VDTSqm47gIAknSvO0nGcnUjQKyn2OkiEdTKS3CdbJBDANkdISS_hhTHW5uzbsiSJVHUy_XvJgajHj0Yb4ojRM5-jPjy3KModnvQbF9v88d5PBmfsubL3wADYh5Zh_VOkbCHRI8Kplqqka-DGnrZuFqrfS16yAMpQgX1L5pu_OZPPY6uFhHgmmiFm64wQAAEigZh8GzntzqtQ_R5bPJp-w"}}
                aterkallad:
                  summary: Återkallad fullmakt
                  value: {"fullmakt": {"id": "b278cd9b-913f-470e-b75c-3406a0f46e53",
                      "ursprung": {"mall": "04130a69-ea74-43b4-b8f4-b456d5032a71"},
                      "rubrik": "Restaurangombud", "beskrivning": "Ombud som får vara
                        behjälpligt att fylla i ansökningar och anmälningar vid start/drift
                        och avslut kringtillstånd att sälja alkohol och tobak i verksamheten.",
                      "skapare": {"id": "195206142597", "typ": "pnr", "namn": "Greger",
                        "fornamn": "Nina"}, "tredjeman": {"id": "2120000829", "namn": "Karlskrona
                          kommun"}, "fullmaktsgivare": {"id": "5561733360", "typ": "orgnr",
                        "namn": "Stora Enso AB"}, "fullmaktsgivarroll": "ORGANISATION",
                      "fullmaktshavare": [{"id": "198101052382", "typ": "pnr", "namn": "Persson",
                          "fornamn": "Test"}], "signatarer": ["fysiskPerson": {"id": "195206142597",
                            "typ": "pnr", "namn": "Greger", "fornamn": "Nina"}], "behorigheter": [
                        {"kod": "6f3440ec-76ef-4a3b-9379-f11f0d76d887", "rubrik": "Anmälan
                            om försäljning och servering av folköl", "beskrivning": "Behörighet
                            att fylla i, signera och skicka in anmälan om folkölsförsäljning."}],
                      "giltigFrom": "2022-09-07", "transportfullmakt": false, "giltigTom": "2024-09-06",
                      "skapadTidpunkt": "2022-09-07T14:24:30.073899+02:00"}, "metadata": {
                      "referensnummer": "MOF0000001553", "registreringstidpunkt": "2022-09-07T14:25:05.983776+02:00",
                      "status": "HISTORISK", "aterkallad": {"part": "FULLMAKTSGIVARE",
                        "person": {"id": "195206142597", "typ": "pnr", "fornamn": "Nina",
                          "namn": "Greger"}, "tidpunkt": "2022-10-14T16:36:52.551019+02:00"},
                      "underskrifter": [{"person": {"id": "195206142597", "typ": "pnr",
                            "namn": "Greger", "fornamn": "Nina"}, "tidpunkt": "2022-09-07T14:25:01.9088902+02:00"}]},
                    "svarstidpunkt": "2022-11-28T13:23:04.346531+01:00", "_sig": {
                      "protected": "eyJraWQiOiI1NTdiMjYyOTZiN2U3ZmJlNDFkMDcxMWIyMWMyZDdiZjg4MDQ1MDdhIiwiYWxnIjoiUlMyNTYifQ",
                      "signature": "U9Y9VT1KZbhtPxo8LQm9454kA0vBJz_iQbNVyuHYkU-tB0SQpNHw3YaGdQiO9Va03InTE-Wu3yD9cs7y4VeLnQPLBkoI_pkdGNBEe6W4Rby_FtWF4bntMPUg6uNRvuqt8VDTSqm47gIAknSvO0nGcnUjQKyn2OkiEdTKS3CdbJBDANkdISS_hhTHW5uzbsiSJVHUy_XvJgajHj0Yb4ojRM5-jPjy3KModnvQbF9v88d5PBmfsubL3wADYh5Zh_VOkbCHRI8Kplqqka-DGnrZuFqrfS16yAMpQgX1L5pu_OZPPY6uFhHgmmiFm64wQAAEigZh8GzntzqtQ_R5bPJp-w"}}
        '404':
          description: Tredjeman eller fullmakt saknas
  /tredjeman/{tredjeman}/jwks:
    parameters:
    - in: path
      name: tredjeman
      required: true
      description: ID för tredje man
      schema:
        $ref: '#/components/schemas/Organisationsnummer'
    get:
      operationId: hamtaTredjemanJwks
      summary: JSON Web Key Set för tredjeman
      tags:
      - signering
      description: |
        Hämta JSON Web Key Set för att kunna verifiera signerade svar från en tredje man.

      responses:
        '200':
          description: JSON Web Key Set för tredjeman
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwkSet'
  /sok/behorigheter:
    post:
      operationId: hamtaBehorigheter
      summary: Sök behörigheter
      description: |
        Hämtar de behörigheter som finns på giltiga fullmakter för fullmaktshavaren.
      tags:
      - fullmakter
      requestBody:
        required: true
        description: Sökparametrar
        content:
          application/json:
            examples:
              alla:
                summary: Alla behörigheter - organisationer
                description: |
                  Hämtar alla fullmaktshavarens behörigheter hos en tredje man
                  där fullmaktsgivaren är en organisation.
                value:
                  tredjeman: "2120000829"
                  fullmaktshavare: {"id": "198101052382", "typ": "pnr"}
                  fullmaktsgivarroll: ["ORGANISATION"]
                  page: {"page": 0, "size": 100}
              fullmaktsgivare:
                summary: Alla behörigheter - specifik fullmaktsgivare
                description: |
                  Hämtar alla fullmaktshavarens behörigheter för en viss fullmaktsgivare och tredje man.
                value:
                  tredjeman: "2120000829"
                  fullmaktshavare: {"id": "198101052382", "typ": "pnr"}
                  fullmaktsgivare: {"id": "5563813962", "typ": "orgnr"}
                  fullmaktsgivarroll: ["ORGANISATION"]
                  page: {"page": 0, "size": 100}
              behorigheter:
                summary: Specifika behörigheter - alla fullmaktsgivare
                description: |
                  Hämtar alla fullmaktshavarens behörigheter för en viss fullmaktsgivare och tredje man.
                value:
                  tredjeman: "2120000829"
                  fullmaktshavare: {"id": "198101052382", "typ": "pnr"}
                  behorigheter: ["5611f2d8-c74e-46e4-aab1-b2f0bd4ce318"]
                  fullmaktsgivarroll: ["ORGANISATION"]
                  page: {"page": 0, "size": 100}
            schema:
              $ref: '#/components/schemas/HamtaBehorigheterRequest'
      responses:
        '200':
          description: Lista med giltiga behörigheter
          content:
            application/json:
              examples:
                some:
                  summary: Behörigheter finns
                  value: {"kontext": [{"tredjeman": "2120000829", "fullmaktsgivare": {
                          "id": "5561733360", "typ": "orgnr", "namn": "Stora Enso
                            AB"}, "fullmaktsgivarroll": "ORGANISATION", "fullmaktshavare": [
                          {"id": "198101052382", "typ": "pnr", "namn": "Persson",
                            "fornamn": "Test"}], "behorigheter": [{"kod": "5947080a-5032-45c5-a243-dd2980ce77d2",
                            "fullmakt": "b278cd9b-913f-470e-b75c-3406a0f46e53"}, {
                            "kod": "6f3440ec-76ef-4a3b-9379-f11f0d76d887", "fullmakt": "b278cd9b-913f-470e-b75c-3406a0f46e53"}],
                        "tidpunkt": "2022-11-28T15:10:11.191523+01:00", "_sig": {
                          "protected": "eyJraWQiOiI1NTdiMjYyOTZiN2U3ZmJlNDFkMDcxMWIyMWMyZDdiZjg4MDQ1MDdhIiwiYWxnIjoiUlMyNTYifQ",
                          "signature": "FU2TSg_o8g-JbRjBA6Xb-xk3QFS4Qarv1qj3nWqouZtaysqbB8Zmq8mgE7fXKR4B6_p-H2sLQXW-POSkGdX5AqW-bNX7TpU1-UoeV73YViSrPCSy7VkkK7dfhr9-s0uhX9E0yoQYUunxICUQRB_HZdwdieEpuSPBzDGzw3z4FFhcs9SMQoAR3YZv1FGMuIZ_r-nHvQ4rwazQyqnYKDVqr63axTtA_W113qzI5mF75s83V4etA3Gv8hH4JP6niu5X9lBRq-CsYyHT_nP0H1TaXYsVC8rDbdnmjX95gSTItsIQuZuBFL2sZyY87Z32otFD7tM5oKvpeDIiKGzajs_YDA"}}],
                    "page": {"size": 100, "number": 0, "totalElements": 1, "totalPages": 1}}
                none:
                  summary: Inga behörigheter
                  value: {"kontext": [], "page": {"number": 0, "size": 20, "totalElements": 0,
                      "totalPages": 0}}
              schema:
                $ref: '#/components/schemas/HamtaBehorigheterResponse'
  /sok/fullmakter:
    post:
      operationId: hamtaFullmakter
      summary: Sök fullmakter
      description: |
        Användarens identitet kan användas för att verifiera behörigheter av systemet som hanterar fullmakter
        för tredje man.
      tags:
      - fullmakter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HamtaFullmakterRequest'
            examples:
              alla:
                summary: Fullmaktshavare
                value: {"fullmaktshavare": {"id": "195308182301", "typ": "pnr"}, "page": {
                    "page": 0, "size": 100}}
              tredjeman:
                summary: Specifik tredje man
                value: {"fullmaktshavare": {"id": "195308182301", "typ": "pnr"}, "tredjeman": "5566789911",
                  "page": {"page": 0, "size": 100}}
              fullmaktsgivare:
                summary: Fullmaktsgivare
                value: {"fullmaktsgivare": {"id": "5566789911", "typ": "orgnr"}, "fullmaktshavare": {
                    "id": "195308182301", "typ": "pnr"}, "tredjeman": "2120000829",
                  "page": {"page": 0, "size": 100}}

      responses:
        '200':
          description: Lista på fullmakter
          content:
            application/json:
              example: {"fullmakter": [{"referensnummer": "MOF0000001553", "registreringstidpunkt": "2022-09-07T14:25:05.983776+02:00",
                    "status": "GILTIG", "vidaredelad": "false", "id": "b278cd9b-913f-470e-b75c-3406a0f46e53",
                    "rubrik": "Restaurangombud", "giltigFrom": "2022-09-07", "giltigTom": "2024-09-06",
                    "tredjeman": "2120000829", "fullmaktsgivare": {"id": "5561733360",
                      "typ": "orgnr", "namn": "Stora Enso AB"}, "fullmaktsgivarroll": "ORGANISATION",
                    "fullmaktshavare": [{"id": "198101052382", "typ": "pnr", "fornamn": "Test",
                        "namn": "Persson"}]}], "page": {"size": 20, "number": 0, "totalElements": 1,
                  "totalPages": 1}}

              schema:
                $ref: '#/components/schemas/HamtaFullmakterResponse'
        '400':
          description: Ogiltig sökning.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth-accept.minaombud.se/auth/realms/dfm/protocol/openid-connect/token
          scopes:
            user:self: Användaren representerar sig själv
            user:any: Maskin-till-maskin utan slutanvändare

    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token
  schemas:
    Any: {}
    ApiError:
      title: ApiError
      type: object
      description: |
        Felinformation.

        Baserad på [RFC 7807](https://tools.ietf.org/html/rfc7807).

        Associeras med `Content-Type: application/problem+json` eller
        `Content-Type: application/json`.

        Producent-tjänster kan sätta attributet `propagate` till `true` eller `false`
        för att forcera att fel propageras (true) eller ersätts med ett generiskt fel (false).
        Om `propagate` inte sätts propageras fel om status är någon av:
        - 400
        - 404
        - 409
        - 422
        - 500
        - 501
        - 503

      properties:
        type:
          type: string
          format: uri
          example: urn:dfm:error:network
          description: |
            Typen av fel.

            Värdet identifierar vilken typ av information (vilka attribut) som förväntas
            finnas i felobjektet.

            Se `ApiErrorType`.

            Lägg till exempel på olika vanligt förekommande kategorier av fel:
            - type, status, code

            Vad sätts de till för ogiltig input (syntax), etc.

        instance:
          type: string
          format: uri
          example: network.timeout
          description: |
            Felkod.

            URI som identifierar denna förekomst av felet

            Anger vilket specifikt fel som har uppstått, till skillnad från
            `type` som indikerar vilka fält som ska finnas i felobjektet och
            används som discriminator.

            Ett visst värde på `instance` är unikt men också associerat med en viss `type`, dvs.
            ett och samma värde ska endaste förekomma med ett värde på `type`.

            Se `ApiErrorCode` för möjliga felkoder.

        status:
          type: integer
          description: HTTP status.
          example: 400

        timestamp:
          type: string
          format: date-time
          description: Datum och tid i ISO 8601-format.
          example: '2021-02-03T13:45:16+01:00'

        requestId: # X-Request-ID
          type: string
          description: |
            Identitet associerad med requesten, vanligtvis via headern X-Request-Id.
          example: d120654c-0d09-481a-8956-940a76474e6b

        title:
          type: string
          example: Address resolution timeout
          description: |
            Kort sammanfattning av felet.

            Lokaliseras men förändras inte för olika förekomster av felet.

        detail:
          type: string
          example: DNS lookup failure for 'example.com' after 10 attempts
          description: |
            Detaljerat beskrivning av detta fel.

            Kan variera mellan förekomster av felet, t.ex. med data från requesten.
            Ej obligatoriskt. Om `detail` saknas bör `title` användas som text istället.

        source:
          type: string
          example: formedlare
          description: |
            Källa till felet. Kan vara en URI eller namn på ett system eller aktör.

            Fördefinierade värden är `producent` som representerar en icke-specifik producent-tjänst
            eller `formedlare` för förmedlaren.

      required:
      - type
      - instance
      - status
      - title

      discriminator:
        propertyName: type
        mapping:
          urn:dfm:error:basic: '#/components/schemas/ApiError'
          urn:dfm:error:network: '#/components/schemas/ApiError'
          urn:dfm:error:validation: '#/components/schemas/ApiErrorValidationError'
          urn:dfm:error:auth: '#/components/schemas/ApiError'

    ApiErrorCode:
      type: string
      description: |
        Välkända felkoder.

        **Generellt**: `urn:dfm:error:basic`
        - `server.error` odefinierat serverfel

        **Åtkomstkontroll**: `urn:dfm:error:auth`
        - `auth.error` odefinierat autentiseringsfel
        - `tredjeman.obehorig` behörighet att utföra request saknas för angiven tredje man
        - `tredjeman.inaktiv` behörighet att utföra request nekas på grund av att tredje man är inaktiverad 
        - `klient.inaktiv` behörighet att utföra request nekas på grund av att klienten är inaktiverad

        **Validering**: `urn:dfm:error:validation`
        - `validation.producer` fel uppstod vid validering av svar från producent
        - `validation.client` fel uppstod vid validering av request från klient

        **Nätverk**: `urn:dfm:error:network`
        - `network.timeout` timeout i nätverkskommunikation eller namnuppslagning
        - `network.error` odefinierat nätverksfel

        **Verksamhetsfel**
        - `fullmakt.behorighet.obligatorisk` - en obligatorisk behörighet saknas
        - `fullmakt.behorighet.duplicerad` - en behörighet är duplicerad
        - `fullmakt.behorighet.ogiltig` - en behörighet är inte giltig för fullmakten (finns inte i mallen eller transportfullmakten)
        - `fullmakt.behorighet.multipla.val` - flera behörighetstyper har valts för en behörighet (både aktiv och passiv)
        - `fullmakt.behorighet.eskalerad` - försök att skicka in en fullmakt baserad på en
           transportfullmakt där en behörighet är aktiv i fullmakt som skickas in och passiv i transportfullmakten
        - `fullmakt.inte.transportfullmakt` - en fullmakt som inte är transportfullmakt försökte användas som transportfullmakt
        - `fullmakt.otillaten.vidaredelning` - försök att dela vidare en fullmakt som inte tillåter vidaredelning
        - `fullmakt.konflikt` - en begärd uppdatering kan inte genomföras pga. konflikt med existerande information
        - `fullmakt.ogiltig` - en fullmakt är ogiltig (fel id, tredje man eller innehåll som avviker från mall eller transportfullmakt)
        - `fullmakt.saknas` - en begärd fullmakt saknas
        - `fullmakt.redan.raderad` - en begärd radering av redan raderad fullmakt
        - `fullmakt.signatar.fysisk_person.ogiltig` - en signatär är ogiltig (ogiltigt personnummer)
        - `fullmakt.signatar.juridisk_person.ogiltig` - en juridisk person är ogiltig (ogiltigt organisationsnummer)
        - `fullmakt.signatarer.saknas` - inga signatärer har pekats ut i fullmakten
        - `fullmaktsgivare.ogiltig` - fullmaktsgivare har ogiltig identitet
        - `fullmaktsgivare.ogiltig_roll` - fullmaktsmallen tillåter inte fullmaktsgivare med denna roll
        - `fullmaktshavare.ogiltig` - fullmaktshavaren har ogiltig identitet
        - `fullmaktshavare.ogiltig_roll` - fullmaktsmallen tillåter inte fullmaktshavare med denna roll
        - `fullmakt.overskriver.max.giltighets.tid` - fullmaktens giltighetstid överskrivs
        - `fullmakt.giltighets.tid.saknas` - fullmaktens giltighetstid saknas
        - `fullmakt.underskrift.ogiltig` - fullmakten är ogiltigt underskriven
        - `fullmakt.underskrift.saknas` - fullmakt saknar underskrift
        - `anvandare.ogiltig` - aktuell användare stämmer inte med fullmaktens skapare
        - `anvandare.obehorig` - aktuell användare är inte behörig att utföra begärd operation
        - `mall.inte.transportfullmakt` - en mall som inte tillåter transportfullmakter försökte användas för en transportfullmakt
        - `mall.ogiltig` - en mall är ogiltig (mismatchande id, tredje man etc.)
        - `mall.saknas` - begärd mall existerar inte
        - `mall.sparrad` - begärd operationen får ej utföras på en spärrad mall
        - `mall.utkast` - begärd operationen får ej utföras på ett utkast
        - `mall.publicerad` - begärd operationen får ej utföras på en publicerad mall
        - `mall.avpublicerad` - begärd operationen får ej utföras på en avpublicerad mall
        - `sokning.havare_givare.saknas` - sökning kräver en fullmaktshavare eller fullmaktsgivare
        - `tredjeman.ogiltig` - begärd tredje man finns inte eller är inte tillåten för anroparen


      enum:
      - auth.error
      - klient.inaktiv
      - fullmakt.behorighet.obligatorisk
      - fullmakt.behorighet.duplicerad
      - fullmakt.behorighet.ogiltig
      - fullmakt.behorighet.multipla.val
      - fullmakt.behorighet.eskalerad
      - fullmakt.inte.transportfullmakt
      - fullmakt.otillaten.vidaredelning
      - fullmakt.konflikt
      - fullmakt.ogiltig
      - fullmakt.overskriver.max.giltighets.tid
      - fullmakt.giltighets.tid.saknas
      - fullmakt.saknas
      - fullmakt.redan.raderad
      - fullmakt.signatar.fysisk_person.ogiltig
      - fullmakt.signatar.juridisk_person.ogiltig
      - fullmakt.signatarer.saknas
      - fullmakt.underskrift.ogiltig
      - fullmakt.underskrift.saknas
      - anvandare.ogiltig
      - anvandare.obehorig
      - fullmaktsgivare.ogiltig
      - fullmaktsgivare.ogiltig_roll
      - fullmaktshavare.ogiltig
      - fullmaktshavare.saknas
      - mall.inte.transportfullmakt
      - mall.sparrad
      - mall.avpublicerad
      - mall.utkast
      - mall.publicerad
      - mall.ogiltig
      - mall.saknas
      - network.timeout
      - network.error
      - server.error
      - sokning.havare_givare.saknas
      - tredjeman.ogiltig
      - tredjeman.obehorig
      - tredjeman.inaktiv
      - validation.producer
      - validation.client

    ApiErrorType:
      description: |
        Välkända feltyper.

        Definierar klasser av fel och indikerar vilka fält som ska finnas
        utöver de som definieras i ApiError.

        - `urn:dfm:error:auth` - åtkomstkontroll, inga utökade fält
        - `urn:dfm:error:basic` - inga specifika utökade fält
        - `urn:dfm:error:network` - nätverksproblem, inga utökade fält
        - `urn:dfm:error:validation` - valideringsfel, se `ApiErrorValidationError`
      type: string
      enum:
      - urn:dfm:error:basic
      - urn:dfm:error:auth
      - urn:dfm:error:network
      - urn:dfm:error:validation

    ApiErrorValidationError:
      title: ApiErrorValidationError
      allOf:
      - $ref: '#/components/schemas/ApiError'
      - type: object
        title: ApiErrorValidationErrorExt
        properties:
          violations:
            description: Detaljerad information om valideringsfel.
            type: array
            items:
              $ref: '#/components/schemas/ValidationError'
        required: [violations]
    AterkalladFullmaktDetaljer:
      description: |
        Information om hur en fullmakt tagits bort.

        Fullmakter kan *återkallas* av fullmaktsgivaren, *återlämnas* av fullmaktshavaren eller *ogiltigförklaras*
        av tredje man.
      type: object
      properties:
        part:
          $ref: '#/components/schemas/FullmaktPart'
        person:
          $ref: '#/components/schemas/NamnIdentitet'
        tidpunkt:
          type: string
          format: date-time
          description: Datum och tid när fullmakten återkallades/återlämnades/ogiltigförklarades.
      required: [part, tidpunkt]
    BehorighetKod:
      type: string
      pattern: '^[\u0021-\u007e\u00a1-\u00ff]*$'
      minLength: 1
      maxLength: 255
      description: Unik kod för en behörighet.
      example: '3fa85f64-5717-4562-b3fc-2c963f66afa6'

    Behorighetskontext:
      type: object
      description: |
        Beskriver en eller flera behörigheter i en kontext med fullmaktsgivare, fullmaktshavare och tredje man.

        Denna information signeras tillsammans med en tidpunkt och kan användas som ett intyg för en behörighet
        under en begränsad tid. 
      properties:
        fullmaktsgivare:
          $ref: '#/components/schemas/Fullmaktsgivare'
        fullmaktsgivarroll:
          $ref: '#/components/schemas/FullmaktsgivareRoll'
        fullmaktshavare:
          type: array
          items:
            $ref: '#/components/schemas/Fullmaktshavare'
          minItems: 1
        tredjeman:
          $ref: '#/components/schemas/Organisationsnummer'
        behorigheter:
          type: array
          items:
            $ref: '#/components/schemas/UtdeladBehorighet'
          minItems: 1
        tidpunkt:
          type: string
          format: date-time
          description: Tidpunkt när informationen sammanställdes
        _sig:
          $ref: '#/components/schemas/JwsSig'
      required:
      - fullmaktsgivare
      - fullmaktsgivarroll
      - fullmaktshavare
      - tredjeman
      - behorigheter
      - tidpunkt
      - _sig

    Behorighetsobjekt:
      type: object
      description: |
        Beskriver behörighet för en fullmaktshavare i en fullmakt.
      properties:
        kod:
          $ref: '#/components/schemas/BehorighetKod'
        rubrik:
          type: string
          minLength: 1
          maxLength: 100
          description: Rubrik på behörighetsobjekt
        beskrivning:
          type: string
          minLength: 1
          maxLength: 500
          description: |
            Ytterligare beskrivning av behörigheter.

            Paragrafer anges som i Markdown genom två på varandra direkt följande radbrytningar.
      required: [kod, rubrik]
    Fornamn:
      type: string
      minLength: 1
      maxLength: 255
      description: Ett förnamn.

    Fullmakt:
      type: object
      description: |
        Definierar den befogenhet en fullmaktshavare har att representera
        en fullmaktsgivare hos en tredje man.
      properties:
        id:
          $ref: '#/components/schemas/FullmaktId'
        ursprung:
          $ref: '#/components/schemas/FullmaktUrsprung'
        rubrik:
          type: string
          minLength: 1
          maxLength: 100
          description: Rubrik på fullmakt.
          example: Rapportera utsläpp
        beskrivning:
          type: string
          minLength: 1
          maxLength: 500
          description: Beskrivning av fullmakt.
          example: Rapportera utsläpp

        giltigFrom:
          type: string
          format: date
          description: Datum som fullmakt gäller från och med.
          #example: '2021-02-10'

        giltigTom:
          type: string
          format: date
          description: Sista datum när fullmakten gäller.
          example:

        skapare:
          $ref: '#/components/schemas/NamnIdentitet'
        skapadTidpunkt:
          type: string
          format: date-time
          description: Datum och tid när fullmakten skapades

        vidaredelning:
          type: boolean
          description: |
            Om fullmakten kan delas vidare av fullmaktshavaren.

            Sedan version 1.2.0.

        transportfullmakt:
          # Beskrivning ändrad i schema 1.1.0 (tagg 1.0.8) att en transportfullmakt
          # är en vidare utdelad fullmakt och inte om den kan transporteras vidare.
          description: |
            Om denna fullmakt tilldelades fullmaktshavaren av en annan fullmaktshavare
            och inte direkt av fullmaktsgivaren
          type: boolean

        fullmaktsgivare:
          $ref: '#/components/schemas/Fullmaktsgivare'
        fullmaktsgivarroll:
          $ref: '#/components/schemas/FullmaktsgivareRoll'
        fullmaktshavare:
          type: array
          items:
            $ref: '#/components/schemas/Fullmaktshavare'
        tredjeman:
          $ref: '#/components/schemas/Tredjeman'
        signatarer:
          description: |
            För en inskickad och godkänd fullmakt de personer som har skrivit under fullmakten.
            De parter som har (inskickad och godkänd fullmakt) eller avses ska skriva under fullmakten.

            Dessa ska återfinnas i de som faktiskt skrivit under fullmakten när den skickas in.
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/FullmaktSignatar'
        behorigheter:
          description: Behörigheter som fullmakten ger.
          type: array
          items:
            $ref: '#/components/schemas/Behorighetsobjekt'
          minItems: 1

      required:
      - id
      - ursprung
      - rubrik
      - beskrivning
      - giltigFrom
      - transportfullmakt
      - fullmaktsgivare
      - fullmaktsgivarroll
      - fullmaktshavare
      - tredjeman
      - behorigheter
      - signatarer
      - skapare
      - skapadTidpunkt

    FullmaktId:
      type: string
      format: uuid
      description: Unikt id på fullmakt.
      example: 'bf31188a-bfbb-4f23-a60a-89c75d009b53'

    FullmaktListItem:
      title: FullmaktListItem
      allOf:
      - $ref: '#/components/schemas/FullmaktMetadataBase'
      - type: object
        title: FullmaktListItemExt
        properties:
          id:
            $ref: '#/components/schemas/FullmaktId'
          rubrik:
            type: string
            minLength: 1
            maxLength: 255
          giltigFrom:
            type: string
            format: date
          giltigTom:
            type: string
            format: date
          tredjeman:
            $ref: '#/components/schemas/Organisationsnummer'
          fullmaktsgivare:
            $ref: '#/components/schemas/Fullmaktsgivare'
          fullmaktsgivarroll:
            $ref: '#/components/schemas/FullmaktsgivareRoll'
          fullmaktshavare:
            type: array
            items:
              $ref: '#/components/schemas/Fullmaktshavare'
          status:
            $ref: '#/components/schemas/FullmaktStatus'
          vidaredelning:
            type: boolean
            description: |
              Om fullmakten kan delas vidare av fullmaktshavaren.

              Sedan version 1.2.0.
          transportfullmakt:
              # Tillagd som icke obligatorisk i 1.2.0
            description: |
              Om denna fullmakt tilldelades fullmaktshavaren av en annan fullmaktshavare
              och inte direkt av fullmaktsgivaren
            type: boolean
        required:
        - id
        - rubrik
        - giltigFrom
        - tredjeman
        - fullmaktsgivare
        - fullmaktsgivarroll
        - fullmaktshavare

    FullmaktMallId:
      type: string
      format: uuid
      description: Unikt id på fullmaktsmall.

    FullmaktMetadata:
      title: FullmaktMetadata
      allOf:
      - $ref: '#/components/schemas/FullmaktMetadataBase'
      - type: object
        title: FullmaktMetadataExt
        properties:
          underskrifter:
            type: array
            items:
              $ref: '#/components/schemas/Underskriftsinformation'
          utdelningar:
            description: |
              Information om vidaredelade transportfullmakter.

              Använd parametern `utdelning` i t.ex. `GET /tredjeman/{tredjeman}/fullmakter/{fullmakt}?utdelning=AKTUELLA`  

              Sedan version 1.2.0.
            type: array
            minItems: 0
            items:
              type: object
              title: FullmaktUtdelning
              properties:
                id:
                  $ref: '#/components/schemas/FullmaktId'
                status:
                  $ref: '#/components/schemas/FullmaktStatus'
                aterkallad:
                  type: boolean
                giltigFrom:
                  type: string
                  format: date
                giltigTom:
                  type: string
                  format: date
                  example:
                vidaredelning:
                  description: Om fullmakten KAN delas vidare av dess fullmaktshavare
                  type: boolean
                vidaredelad:
                  description: Om fullmakten HAR delats vidare av dess fullmaktshavare
                  type: boolean
                fullmaktshavare:
                  type: array
                  items:
                    $ref: '#/components/schemas/Fullmaktshavare'
              required:
              - id
              - status
              - aterkallad
              - giltigFrom
              - vidaredelning
              - vidaredelad
              - fullmaktshavare
        required:
        - underskrifter


    FullmaktMetadataBase:
      type: object
      properties:
        referensnummer:
          type: string
          minLength: 1
          maxLength: 150
          description: |
            Denna referens är tänkt att vara en referens som är mer
            praktisk att kommunicera mellan kund och tredje man.
            Visas efter inskickad fullmakt. Är unikt för alla fullmakter
            MOP -> givare person
            MOF -> givare Företag            
          example: MOF1234567890
        registreringstidpunkt:
          type: string
          format: date-time
          description: Datum och tid när fullmakten registrerades
          example: '2021-01-10'
        aterkallad:
          $ref: '#/components/schemas/AterkalladFullmaktDetaljer'
        status:
          $ref: '#/components/schemas/FullmaktStatus'
        vidaredelad:
          type: boolean
          description: |
            Om denna fullmakt har delats vidare av fullmaktshavaren som en transportfullmakt.

            Sedan version 1.2.0.
      required:
      - referensnummer
      - status

    FullmaktMetadataResponse:
      type: object
      title: FullmaktMetadataResponse
      properties:
        fullmakt:
          $ref: '#/components/schemas/Fullmakt'
        metadata:
          $ref: '#/components/schemas/FullmaktMetadata'
        svarstidpunkt:
          type: string
          format: date-time
          description: Datum och tid när svaret genererades.
          example: '2021-02-03T13:45:16+01:00'
        _sig:
          $ref: '#/components/schemas/JwsSig'
      required: [fullmakt, metadata, svarstidpunkt, _sig]
    FullmaktPart:
      description: Anger vilken part (fullmaktsgivare, fullmaktshavare eller tredjeman)
        som agerar med fullmakten
      type: string
      enum:
      - FULLMAKTSHAVARE
      - FULLMAKTSGIVARE
      - TREDJEMAN
      - UTDELARE
      example: FULLMAKTSGIVARE

    FullmaktSignatar:
      description: |
        En part som ska skriva under en fullmakt.

        Attributet `fysiskPerson` används när en fysisk person ska skriva under för sig själv.

        Attributet `juridiskSignatar` används när företrädare för en juridisk person ska skriva under.
        När en person skriver under som företrädare för en juridisk person
        så anger attributet `juridiskSignatar.juridiskPerson` den juridiska person som den
        fysiska personen representerar och `juridiskSignatar.foretradare` de som representerar den
        juridiska personen. Samma fysiska person kan förekomma flera gånger som signatär
        men som företrädare för olika juridiska personer.
      type: object
      title: FullmaktSignatar
      properties:
        fysiskPerson:
          $ref: '#/components/schemas/FysiskPerson'
        juridiskSignatar:
          type: object
          title: FullmaktJuridiskSignatar
          properties:
            juridiskPerson:
              $ref: '#/components/schemas/JuridiskPerson'
            foretradare:
              type: array
              items:
                $ref: '#/components/schemas/FysiskPerson'
          required: [juridiskPerson, foretradare]
    FullmaktStatus:
      type: string
      title: FullmaktStatus
      description: |
        Fullmakten kan vara
        - *historisk* - inaktuell, återlämnad, etc.
        - *aktuell* - aktuellt datum är tidigare eller lika med fullmaktens sista giltighetsdatum (datum <= tom)
        - *giltig* - aktuellt datum är inom fullmaktens giltighetsperiod (from <= datum <= tom)
      enum:
      - HISTORISK
      - AKTUELL
      - GILTIG

    FullmaktUrsprung:
      title: FullmaktUrsprung
      type: object
      description: |
        Referens till en mall och för transportfullmakter den fullmakt transportfullmakten baseras på.
      properties:
        mall:
          $ref: '#/components/schemas/FullmaktMallId'
        fullmakt:
          $ref: '#/components/schemas/FullmaktId'
      required: [mall]
    Fullmaktsgivare:
      title: Fullmaktsgivare
      description: Fullmaktsgivare med namn och identitet.
      allOf:
      - $ref: '#/components/schemas/NamnIdentitet'
      example: {"id": "5560038860", "typ": "orgnr", "namn": "Testbolag AB"}
    FullmaktsgivareRoll:
      description: Anger om en fullmakt utfärdas i roll som privatperson eller organisation.
      type: string
      enum:
      - PRIVAT
      - ORGANISATION
      example: ORGANISATION

    Fullmaktshavare:
      title: Fullmaktshavare
      description: Fullmaktshavare med namn och identitet.
      allOf:
      - $ref: '#/components/schemas/NamnIdentitet'
      example: {"id": "197309069289", "typ": "pnr", "fornamn": "Nina", "namn": "Greger"}
    FysiskPerson:
      title: FysiskPerson
      description: Fysisk person med namn och identitet.
      allOf:
      - $ref: '#/components/schemas/NamnIdentitet'
      example: {"id": "197309069289", "typ": "pnr", "fornamn": "Nina", "namn": "Greger"}
    HamtaBehorigheterRequest:
      title: HamtaBehorigheterRequest
      type: object
      description: |
        En sökning görs för en fullmaktshavare och kan filtreras på fullmaktsgivare.
        ny parameter tillkommer status:
          aktuell = ej återkallad och tom datum = null eller större och lika med dagen datum
          historisk = återkallad eller tom datum mindre än dagen datum
        Sökningar via centraltjänsten kan filtreras på tredje man.
      properties:
        fullmaktshavare:
          $ref: '#/components/schemas/Identitetsbeteckning'
        fullmaktsgivare:
          $ref: '#/components/schemas/Identitetsbeteckning'
        fullmaktsgivarroll:
          type: array
          items:
            $ref: '#/components/schemas/FullmaktsgivareRoll'
          minItems: 1
        tredjeman:
          $ref: '#/components/schemas/Organisationsnummer'
        behorigheter:
          description: Möjlighet att filtera på en delmängd av behörigheter.
          type: array
          items:
            $ref: '#/components/schemas/BehorighetKod'
          minItems: 1
        page:
          $ref: '#/components/schemas/PageParameters'
      required: [fullmaktshavare, tredjeman]
    HamtaBehorigheterResponse:
      title: HamtaBehorigheterResponse
      description: |
        Lista med behörigheter hos en tredje man, samt information om fullmaktsgivare.

        Behörigheterna är de behörigheter som var gällande vid tidpunkten
        i begäran.

        Mer information om fullmaktsgivare tillhandahålls separat
        från listan med behörigheter.

        Pagineringsinformation gäller listan med fullmaktsgivare och är ordnad
        i stigande ordning på namn. (TODO: parametrisera sorteringsattribut?)
      type: object
      properties:
        kontext:
          type: array
          items:
            $ref: '#/components/schemas/Behorighetskontext'
        page:
          $ref: '#/components/schemas/PageMetadata'
      required: [kontext, page]
    HamtaFullmakterRequest:
      title: HamtaFullmakterRequest
      type: object
      description: |
        Sortering kan begäras på attributen:
        - fullmaktshavare (namn)
        - fullmaktsgivare (namn)
        - giltigFrom
        - giltigTom
        - referensnummer
        - rubrik
        - tredjeman (namn)

        Standardsorteringen är `rubrik,tredjeman,fullmaktsgivare,fullmaktshavare,giltigFrom,referensnummer`.
      properties:
        fullmaktshavare:
          $ref: '#/components/schemas/Identitetsbeteckning'
        fullmaktsgivare:
          $ref: '#/components/schemas/Identitetsbeteckning'
        fullmaktsgivarroll:
          type: array
          items:
            $ref: '#/components/schemas/FullmaktsgivareRoll'
          minItems: 1
        tredjeman:
          type: array
          items:
            $ref: '#/components/schemas/Organisationsnummer'
          minItems: 1
        status:
          $ref: '#/components/schemas/FullmaktStatus'
        aterkallad:
          type: boolean
          description: |
            Ange true/false för att filtrera på återkallade/inte återkallade fullmakter.
        referenstidpunkt:
          type: string
          format: date-time
          description: |
            Datum och tid som används för datumkontroller istället för dagens datum
            för att avgöra en fullmakts status (aktuell, giltig eller historisk).
        giltigFrom:
          type: string
          format: date
          description: |
            Fullmakten måste börja gälla vid eller senare än detta datum.

            Detta är en absolut datumkontroll och påverkas inte av referenstidpunkt.
        giltigTom:
          type: string
          format: date
          nullable: true
          description: |
            Fullmakten måste sluta gälla vid eller tidigare än detta datum.

            Om värdet är null så inkluderas bara de fullmakter som saknar
            sista giltighetsdag.

            Detta är en absolut datumkontroll och påverkas inte av referenstidpunkt.
        ursprung:
          type: string
          format: uuid
          nullable: true
          description: |
            Sök på fullmakter med detta fullmaktsid som ursprung.

            Ange `null` för att begära rotfullmakter.
        page:
          $ref: '#/components/schemas/PageParameters'
      required: []
      example: {"fullmaktshavare": {"id": "195308182301", "typ": "pnr"}, "tredjeman": "5566789911",
        "page": {"page": 0, "size": 100, "sort": "giltigFrom desc"}}
    HamtaFullmakterResponse:
      title: HamtaFullmakterResponse
      type: object
      properties:
        fullmakter:
          type: array
          items:
            $ref: '#/components/schemas/FullmaktListItem'
        problem:
          type: object
          description: |
            Objekt med problem där nyckeln är id för en tredje man och värdet
            anger problemet.

            Tredje man ska INTE returnera värden för problem utan ska istället
            kommunicera problemet via HTTP med en status != 200 och problemet
            som payload. Eventuella problem hos tredje man sammanställs av den
            centrala fullmaktstjänsten och returneras via detta attribut.
          additionalProperties:
            $ref: '#/components/schemas/ApiError'
          default: {}
          example: {"5566789911": {"type": "urn:dfm:error:network", "instance": "network.error",
              "timestamp": "2021-02-03T13:45:16+01:00", "title": "Network error",
              "status": 500}}
        page:
          $ref: '#/components/schemas/PageMetadata'
      required: [fullmakter, page]
    Identitetsbeteckning:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Identitetsnummer'
        typ:
          $ref: '#/components/schemas/Identitetstyp'
      required: [id, typ]
      example:
        id: "198101052382"
        typ: "pnr"

    Identitetsnummer:
      type: string
      minLength: 1
      description: |
        Personnummer, organisationsnummer etc.

        Identiteten är inte formaterad med t.ex. bindestreck.

    Identitetstyp:
      type: string
      description: |
        Typ av identitet
        | Typ        | Identitet           | Kommentar             |   
        |------------|---------------------|-----------------------|
        | `pnr`      | Personnummer        | 12 siffror            |
        | `orgnr`    | Organisationsnummer | 10 siffror (inget 16-prefix). OBS: används *INTE* för enskilda näringsidkare, där används respektive identitet för personen. |
        | `samnr`    | Samordningsnummer   | 12 siffror            |
        | `gdnr`     | GD-nummer           | 10 siffror            |

    JuridiskPerson:
      title: JuridiskPerson
      description: Juridisk person med namn och identitet.
      allOf:
      - $ref: '#/components/schemas/NamnIdentitet'
      example: {"id": "5560038860", "typ": "orgnr", "namn": "Testbolag AB"}
    Jwk:
      title: Jwk
      type: object
      description: Enligt RFC 7517
      properties:
        kty:
          type: string
          example: RSA
        use:
          type: string
          example: sig
        key_ops:
          type: array
          items:
            type: string
        alg:
          type: string
          example: RSA
        kid:
          type: string
          example: '78b4cf23656dc395364f1b6c02907691f2cdffe1'
        x5u:
          type: string
          format: uri
        x5c:
          type: array
          items:
            type: string
        x5t:
          type: string
        'x5t#S256':
          type: string
      required: [kty]
      additionalProperties: true

    JwkSet:
      title: JwkSet
      type: object
      description: Enligt RFC 7517
      properties:
        keys:
          type: array
          items:
            $ref: '#/components/schemas/Jwk'
      required: [keys]
      example: {"keys": [{"kty": "RSA", "e": "AQAB", "use": "sig", "kid": "MzYxMmFkOGYwMWI0ZWNmNDcxNGYwYmM4ZTA3MWI2NDAzZGQzNGM0ZGRlNjJkODFkZDRiOTFkMWFhMzU2ZGVlNg_RS256",
            "alg": "RS256", "n": "xeqoZYbQ_Sr8DOFQ-_qbEbCp6Vzb5hzH7oa3hf2FZxRKF0H6b8COMzz8-0mvEdYVvb_31jMEL2CIQhkQRol1IruD6nBOmkjuXJSBficklMaJZORhuCrB4roHxzoG19aWmscA0gnfBKo2oGXSjJmnZxIh-2X6syHCfyMZZ00LzDyrgoXWQXyFvCA2ax54s7sKiHOM3P4A9W4QUwmoEi4HQmPgJjIM4eGVPh0GtIANN-BOQ1KkUI7OzteHCTLu3VjxM0sw8QRayZdhniPF-U9n3fa1mO4KLBsW4mDLjg8R_JuAGTX_SEEGj0B5HWQAP6myxKFz2xwDaCGvT-rdvkktOw"}]}
    JwsSig:
      title: JwsSig
      type: object
      description: Enligt RFC 7515
      properties:
        protected:
          type: string
          format: base64url
          description: JWS Protected Header
        header:
          type: object
          description: JWS Unprotected Header
          additionalProperties: true
        signature:
          type: string
          format: base64url
      required:
      - signature

    Namn:
      type: string
      minLength: 1
      maxLength: 255
      description: Ett namn.

    NamnIdentitet:
      title: NamnIdentitet
      description: Namn och identitet på en person, organisation eller användare.
      allOf:
      - $ref: '#/components/schemas/Identitetsbeteckning'
      - $ref: '#/components/schemas/Namngiven'
    Namngiven:
      type: object
      title: Namngiven
      description: För- och efternamn eller organisationsnamn
      properties:
        fornamn:
          $ref: '#/components/schemas/Fornamn'
        namn:
          $ref: '#/components/schemas/Namn'
      required: [namn]
    Organisationsnummer:
      type: string
      pattern: '^\d{10}$'
      description: Organisationsnummer för juridisk person
      externalDocs:
        description: Information om organisationsnummer från Skatteverket
        url: 
          https://www.skatteverket.se/foretagochorganisationer/foretagare/startaochregistrera/organisationsnummer.4.361dc8c15312eff6fd235d1.html
      example: '2120000829'

    PageMetadata:
      description: |
        Objekt som returneras tillsammans med paginerade samlingar.
      type: object
      properties:
        size:
          type: integer
          format: int32
          description: Antal element per sida
          example: 20
        number:
          type: integer
          format: int32
          description: Sidnummer
          example: 0
        totalElements:
          type: integer
          format: int64
          description: Totalt antal element
          example: 101
        totalPages:
          type: integer
          format: int64
          description: Totalt antal sidor
          example: 6
    PageNumberParameter:
      type: integer
      format: int32
      minimum: 0
      description: 0-baserat sidnummer för paginering (page-parameter).
      example: 0

    PageParameters:
      description: |
        Parametrar för paginerade requests.
      type: object
      properties:
        page:
          $ref: '#/components/schemas/PageNumberParameter'
        size:
          $ref: '#/components/schemas/PageSizeParameter'
        sort:
          type: string
          description: |
            Komma-separerad lista med sorteringsattribut och riktningar.

            | sort                         | beskrivning |
            |------------------------------|-------------|
            | namn                         | Sortera på namn i stigande ordning  |
            | namn desc                    | Sortera på namn i omvänd ordning | 
            | fornamn,efternamn            | Sortera på fornamn och efternamn | 
            | namn ignorecase              | Sortera på namn i stigande ordning utan hänsyn till stora/små bokstäver | 
            | namn desc ignorecase         | Sortera på namn i omvänd ordning utan hänsyn till stora/små bokstäver | 
      example: {"page": 0, "size": 20, "sort": ""}
    PageSizeParameter:
      type: integer
      format: int32
      minimum: 1
      description: Storlek på sidor för paginering (size-parameter).
      example: 20

    Tredjeman:
      title: Tredjeman
      description: Namn och organisationsnummer för en tredje man.
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Organisationsnummer'
        namn:
          $ref: '#/components/schemas/Namn'
      required: [id, namn]
      example: {"id": "2120000829", "namn": "Karlskrona Kommun"}
    Underskriftsinformation:
      type: object
      title: Underskriftsinformation
      description: Person och tidpunkt för en underskrift.
      properties:
        person:
          $ref: '#/components/schemas/FysiskPerson'
        tidpunkt:
          type: string
          format: date-time
          description: Tidpunkt när personen skrev under
      required: [person, tidpunkt]
    UtdeladBehorighet:
      title: UtdeladBehorighet
      description: |
        Behörighet för en fullmaktshavare hos en fullmaktsgivare.

        Attributet `kod` identifierar behörigheten och attributet `fullmakt`
        är en referens till den fullmakt som behörigheten grundas i.

        Om flera fullmakter ger samma behörighet så refereras till den den fullmakt
        som gäller från senaste datum.

        Fullmakter som inte är giltiga vid tidpunkt för requesten beaktas inte.

        Exempel:
        | fullmakt | kod | giltigFrom |
        |----------|-----|------------|
        | 1        | x   | 2021-01-01 |
        | 2        | x   | 2021-02-01 |
        | 3        | x   | 2021-03-01 |

        Ovanstående tre fullmakter ger slutgiltig behörighet:
        ```json
        {
          "kod": "x",
          "fullmakt": "2"
        }
        ```

      type: object
      properties:
        kod:
          $ref: '#/components/schemas/BehorighetKod'
        fullmakt:
          $ref: '#/components/schemas/FullmaktId'
      required: [kod, typ, fullmakt]
    ValidationError:
      title: ValidationError
      type: object
      properties:
        message:
          type: string
          example: must not be null
        path:
          type: string
          example: nested.property
        value:
          $ref: '#/components/schemas/Any'
      required:
      - message
      - path

